export const ReatilMockData = [
	{
		id: 1,
		name: 'Electronics Store',
		phoneNumber: '123-456-789',
		email: 'info@elefgdfgdgfdggdfgdsfsfdsfsfdsfsdfdfgctronics.com',
		website: 'https://electronics.com',
		storeTypeId: 1,
		stateId: 1,
		countyId: 1,
		cityId: 1,
		suburbId: 1,
		address: '123 Main St',
		latitude: 40.7128,
		longitude: -74.006,
		categories: [1, 2],
		viewCount: 100,
		isSubscribedForAds: true,
	},
	{
		id: 2,
		name: 'Furniture Store',
		phoneNumber: '987-654-321',
		email: 'contact@furniture.com',
		website: 'https://furniture.com',
		storeTypeId: 2,
		stateId: 1,
		countyId: 1,
		cityId: 1,
		suburbId: 1,
		address: '456 Second St',
		latitude: 34.0522,
		longitude: -118.2437,
		categories: [3],
		viewCount: 200,
		isSubscribedForAds: false,
	},
	{
		id: 3,
		name: 'Furniture Store',
		phoneNumber: '987-654-321',
		email: 'contact@furniture.com',
		website: 'https://furniture.com',
		storeTypeId: 2,
		stateId: 1,
		countyId: 1,
		cityId: 1,
		suburbId: 1,
		address: '456 Second St',
		latitude: 34.0522,
		longitude: -118.2437,
		categories: [3],
		viewCount: 200,
		isSubscribedForAds: false,
	},
	{
		id: 4,
		name: 'Furniture Store',
		phoneNumber: '987-654-321',
		email: 'contact@furniture.com',
		website: 'https://furniture.com',
		storeTypeId: 2,
		stateId: 1,
		countyId: 1,
		cityId: 1,
		suburbId: 1,
		address: '456 Second St',
		latitude: 34.0522,
		longitude: -118.2437,
		categories: [3],
		viewCount: 200,
		isSubscribedForAds: false,
	},
];
